from __future__ import annotations
from typing import TYPE_CHECKING, Any, Iterable, Protocol, TypeVar

T = TypeVar('T')

if TYPE_CHECKING:
    from aiomysql import Connection


class Repository(Protocol[T]):
    """<<interface>>

    Generic[T]
    """
    async def insert(self, entities: Iterable[T], conn: None | Connection = None) -> int: ...
    async def exists(self, id_: Any, conn: None | Connection = None) -> bool: ...
    async def count(self, conn: None | Connection = None) -> float: ...
    async def find_one(self, id_: Any, conn: None | Connection = None) -> None | T: ...
    async def find_all(self, conn: None | Connection = None) -> None | list[T]: ...
    async def update(self, entities: Iterable[T], conn: None | Connection = None) -> int: ...
    async def delete(self, id_: Any, conn: None | Connection = None) -> int: ...
    async def create_table(self, conn: None | Connection = None) -> None: ...
    @property
    def table_name(self) -> str: ...
