from __future__ import annotations
from typing import Any, Protocol


class RatelimitHandler(Protocol):
    async def limit(self) -> None: ...
    async def ratelimited(self) -> None: ...
    def update(self, headers: dict[str, Any]) -> None: ...
    @property
    def min_limit(self) -> int: ...
    @property
    def remaining(self) -> int: ...
    @property
    def total(self) -> int: ...
    @property
    def reset(self) -> float: ...
