from typing import Protocol


class Task(Protocol):
    """<<interface>>"""
    def run(self) -> None: ...
    @property
    def first_delay(self) -> float: ...
    @property
    def interval(self) -> float: ...
    @property
    def name(self) -> str: ...
