from __future__ import annotations
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from kans import GuildEndpoint, PlayersEndpoint, PlayerEndpoint


class Api(Protocol):
    """<<interface>>"""
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    @property
    def guild(self) -> GuildEndpoint: ...
    @property
    def players(self) -> PlayersEndpoint: ...
    @property
    def player(self) -> PlayerEndpoint: ...
    async def __aenter__(self) -> Api: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any): ...
